apiVersion: v2
name: pagopadomainbuilder
description: Microservice description
type: application
version: 0.204.0
appVersion: 0.1.0-1-fix-gha
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
