apiVersion: v2
name: pagopadomainbuilder
description: Microservice description
type: application
version: 1.8.0
appVersion: 1.0.4
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
